"""Export the benchmark's generated glyph catalog for every screensaver port.

One command regenerates the web data (glyphs.js), the Windows C# data file
(windows/GlyphData.cs), and the macOS resource (macos/glyphs.json), so all
three ports render the same framework-generated catalog. Run from the
repository root after any glyph grammar change:

    python screensaver/export_glyphs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from benchmarks.glyph_screensaver_assets import CANVAS_H, CANVAS_W, GLYPH_SPECS

HEADER = "Generated by screensaver/export_glyphs.py from the Smythe glyph "


def _payload() -> dict:
    return {
        "canvas": [CANVAS_W, CANVAS_H],
        "strokes": [[list(stroke) for stroke in spec.strokes] for spec in GLYPH_SPECS],
        "speeds": [spec.speed for spec in GLYPH_SPECS],
        "trails": [spec.trail_length for spec in GLYPH_SPECS],
    }


def _write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {destination} ({destination.stat().st_size} bytes)")


def _csharp(data: dict) -> str:
    # Strokes become jagged float arrays; the kind is encoded as
    # 0 = line, 1 = quadratic, 2 = dot, followed by the numeric values.
    kind_codes = {"l": 0, "q": 1, "d": 2}
    glyphs = []
    for strokes in data["strokes"]:
        rows = []
        for stroke in strokes:
            values = [str(kind_codes[stroke[0]])] + [f"{v}f" for v in stroke[1:]]
            rows.append("new float[]{" + ",".join(values) + "}")
        glyphs.append("new float[][]{" + ",".join(rows) + "}")
    speeds = ",".join(f"{v}f" for v in data["speeds"])
    trails = ",".join(str(v) for v in data["trails"])
    return (
        f"// {HEADER}benchmark's GLYPH_SPECS. Do not edit by hand.\n"
        "namespace SmytheGlyphRain\n{\n"
        "    internal static class GlyphData\n    {\n"
        f"        public const float CanvasW = {data['canvas'][0]}f;\n"
        f"        public const float CanvasH = {data['canvas'][1]}f;\n"
        "        public static readonly float[][][] Strokes = new float[][][]\n"
        "        {\n            " + ",\n            ".join(glyphs) + "\n        };\n"
        f"        public static readonly float[] Speeds = new float[]{{{speeds}}};\n"
        f"        public static readonly int[] Trails = new int[]{{{trails}}};\n"
        "    }\n}\n"
    )


def main() -> None:
    root = Path(__file__).parent
    data = _payload()
    compact = json.dumps(data, separators=(",", ":"))
    _write(
        root / "glyphs.js",
        f"// {HEADER}benchmark's GLYPH_SPECS. Do not edit by hand.\n"
        f"const GLYPHS={compact};\n",
    )
    _write(root / "windows" / "GlyphData.cs", _csharp(data))
    _write(root / "macos" / "glyphs.json", compact + "\n")


if __name__ == "__main__":
    main()
