"""Export the current filled-contour catalog for the layered Canvas web view.

Native ports use the same SVG catalog. Export those separately with
``python screensaver/export_native_glyphs.py``:

    python screensaver/export_glyphs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from benchmarks.noumenon_assets import GLYPH_SPECS

HEADER = "Generated by screensaver/export_glyphs.py from the current SVG catalog."


def _payload() -> dict:
    catalog = json.loads((Path(__file__).parent / "glyph-design-v2/catalog.json").read_text(
        encoding="utf-8"))
    return {
        "canvas": catalog["canvas"], "version": catalog["version"],
        "catalog_sha256": catalog["catalog_sha256"],
        "paths": [glyph["paths"] for glyph in catalog["glyphs"]],
        "speeds": [spec.speed for spec in GLYPH_SPECS],
        "trails": [spec.trail_length for spec in GLYPH_SPECS],
    }


def _write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {destination} ({destination.stat().st_size} bytes)")


def main() -> None:
    root = Path(__file__).parent
    data = _payload()
    compact = json.dumps(data, separators=(",", ":"))
    _write(
        root / "glyphs.js",
        f"// {HEADER} Do not edit by hand.\n"
        f"const GLYPHS={compact};\n",
    )


if __name__ == "__main__":
    main()
