"""Export the historical stroke catalog for the legacy web view only.

Native ports use the current SVG catalogs. Export those separately with
``python screensaver/export_native_glyphs.py``. This command cannot overwrite
native data with the historical stroke programs:

    python screensaver/export_glyphs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1]))

from benchmarks.glyph_screensaver_assets import CANVAS_H, CANVAS_W, GLYPH_SPECS

HEADER = "Generated by screensaver/export_glyphs.py from the Smythe glyph "


def _payload() -> dict:
    return {
        "canvas": [CANVAS_W, CANVAS_H],
        "strokes": [[list(stroke) for stroke in spec.strokes] for spec in GLYPH_SPECS],
        "speeds": [spec.speed for spec in GLYPH_SPECS],
        "trails": [spec.trail_length for spec in GLYPH_SPECS],
    }


def _write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {destination} ({destination.stat().st_size} bytes)")


def main() -> None:
    root = Path(__file__).parent
    data = _payload()
    compact = json.dumps(data, separators=(",", ":"))
    _write(
        root / "glyphs.js",
        f"// {HEADER}benchmark's GLYPH_SPECS. Do not edit by hand.\n"
        f"const GLYPHS={compact};\n",
    )


if __name__ == "__main__":
    main()
